---
- name: run Windows tasks
  include_tasks: windows/main.yml
  when: ansible_os_family == "Windows"

- name: run GNU/Linux tasks
  include_tasks: linux/main.yml
  when: ansible_os_family != "Windows"
