---
- name: Prepare proxy config
  hosts: all
  gather_facts: false
  roles:
    - role: stone-payments.proxy
  vars:
    proxy_address: "example.com"
    proxy_port: "3128"
    proxy_whitelist:
      - ".google.com"
      - "wikipedia.com"
