---
- name: remove legacy proxy settings
  win_regedit:
    path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Internet Settings
    name: "{{ item }}"
    state: absent
  with_items:
    - ProxySettingsPerUser
    - ProxyEnable
    - ProxyServer
    - ProxyOverride

- name: remove updated applications proxy settings
  win_dsc:
    resource_name: xProxySettings
    IsSingleInstance: 'Yes'
    Ensure: Absent
    EnableAutoDetection: true
    EnableAutoConfiguration: true
    EnableManualProxy: false
