---
- name: enforce uniform proxy settings for all user accounts
  win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\CurrentVersion\Internet Settings
    name: ProxySettingsPerUser
    type: dword
    data: 0
    state: present

- name: configure legacy applications to use the system proxy
  win_regedit:
    path: HKLM:\SOFTWARE{{ item.0 }}\Microsoft\Windows\CurrentVersion\Internet Settings
    name: "{{ item.1.name }}"
    type: "{{ item.1.type }}"
    data: "{{ item.1.data }}"
    state: present
  with_nested:
    - - ""
      - \WOW6432Node
    - - name: ProxyEnable
        type: dword
        data: 1
      - name: ProxyServer
        type: string
        data: "{{ 'socks=' if 'socks' in proxy_proto else '' }}{{ proxy_address }}:{{ proxy_port }}"
      - name: ProxyOverride
        type: string
        data: "{{ (proxy_whitelist + ['<local>']) | join(';') }}"

- name: configure updated applications to use the system proxy
  win_dsc:
    resource_name: xProxySettings
    IsSingleInstance: 'Yes'
    Ensure: Present
    EnableAutoDetection: false
    EnableAutoConfiguration: false
    EnableManualProxy: true
    ProxyServer: "{{ 'socks=' if 'socks' in proxy_proto else '' }}{{ proxy_address }}:{{ proxy_port }}"
    ProxyServerExceptions: "{{ proxy_whitelist | join(';') }}"
    ProxyServerBypassLocal: true
